plugins {
    id 'java-library'
    id 'fabric-loom'
}

repositories {
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        name = "Fabric"
        url = "https://maven.fabricmc.net/"
    }
    mavenCentral()
}

dependencies {
    api project(":compat-api")
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modCompileOnly "maven.modrinth:openboatutils:${project.obu_legacy_version}"
    compileOnly "net.fabricmc:sponge-mixin:0.12.5+mixin.0.8.5"
    modCompileOnly "net.fabricmc:fabric-loader:${project.loader_version}"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
    withSourcesJar()
}
